# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 676ea6c11c267e64bfebe5e004242df4d9078a547fbee59e61dbb70947df88badf577fa7936d121ca0779ca98d6d453ae1aca29c489a32a25caad085a0919122

test:
  secret_key_base: bcaba33522b947426533664ce4aa5e952cfde562322a3c79485e3bad915f4b4a119bd7001f61fe41ea6332ff33c0d7ede21c6354d81ab3e444da2cb2695f3f0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
